import { useState, useEffect } from "react";

export function useCodeScreen(files) {
  const [consoleState, setConsoleState] = useState(false);
  const [consoleOutput, setConsoleOutput] = useState([]);
  const [previewContent, setPreviewContent] = useState("");
  const [previewVisible, setPreviewVisible] = useState(false);

  const generatePreview = (files) => {
    const htmlFile = files.find((f) => f.name === "index.html");
    const cssFile = files.find((f) => f.name === "index.css") || files.find((f) => f.name === "styles.css");
    const jsFile = files.find((f) => f.name === "index.js") || files.find((f) => f.name === "script.js");

    if (htmlFile) {
      let combinedContent = htmlFile.content;
      
      combinedContent = combinedContent.replace(/<link[^>]*rel=['"]stylesheet['"][^>]*>/gi, '');
      combinedContent = combinedContent.replace(/<script[^>]*src=['"][^'"]*\.js['"][^>]*><\/script>/gi, '');

      combinedContent = combinedContent.replace(
        "</head>",
        `  <script crossorigin src="https://cdn.jsdelivr.net/npm/react@18/umd/react.development.js"></script>
  <script crossorigin src="https://cdn.jsdelivr.net/npm/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@babel/standalone/babel.min.js"></script>
  </head>`
      );

      if (cssFile) {
        combinedContent = combinedContent.replace(
          "</head>",
          `  <style>\n${cssFile.content}\n  </style>\n</head>`
        );
      }

      if (jsFile) {
        combinedContent = combinedContent.replace(
          "</body>",
          `  <script type="text/babel" >\n${jsFile.content}\n  </script>\n</body>`
        );
      }

      return combinedContent;
    }
    return "";
  };

  useEffect(() => {
    if (previewVisible) {
      const content = generatePreview(files);
      if (content) {
        setPreviewContent(content);
      }
    }
  }, [files, previewVisible]);

  const runCode = (files) => {
    setConsoleOutput([]);
    const originalLog = console.log;
    const outputs = [];
    console.log = (...args) => {
      outputs.push(args.join(" "));
      originalLog(...args);
    };

    const jsFile = files.find((f) => f.name.endsWith('.js') && f.active);

    if (jsFile) {
      try {
        const executeCode = new Function(jsFile.content);
        executeCode(); 
        setConsoleOutput(outputs);
      } catch (error) {
        if (error.message.includes("Unexpected token '<'")) {
          setConsoleOutput([
            "Note: This console is for pure JavaScript output. If you're trying to observe React JS behavior, please use the preview to see the output.",
            `However, any JavaScript console output generated by React Js code will still be visible in the browser's console.`,
          ]);
        } else {
          setConsoleOutput([`Error: ${error.message}`]);
        }
      } finally {
        console.log = originalLog;
        if (outputs.length === 0) {
          setConsoleOutput(["Please use console.log() to see output"]);
        }
      }
    } else {
      setConsoleOutput(["Error: No .js file found!"]);
    }
    setConsoleState(true);
    hidePreview();
  };

  const showPreview = () => {
    const content = generatePreview(files);
    if (content) {
      setPreviewContent(content);
      setPreviewVisible(true);
    } else {
      alert("index.html file not found!");
    }
  };

  const toggleConsole = () => {
    if (previewVisible) {
      setPreviewVisible(false);
    } else {
      setPreviewVisible(true);
    }
    if (consoleState) {
      setConsoleState(false);
    } else {
      setConsoleState(true);
    }
  };

  const hidePreview = () => {
    setPreviewVisible(false);
  };

  const showConsole = () => {
    setConsoleState(true);
  };

  return {
    consoleState,
    setConsoleState,
    consoleOutput,
    setConsoleOutput,
    runCode,
    showConsole,
    
    previewContent,
    previewVisible,
    showPreview,
    hidePreview,
    
    toggleConsole,
  };
}
