import { useState, useEffect } from "react";

export function useCodeScreen(files) {
  const [consoleState, setConsoleState] = useState(false);
  const [consoleOutput, setConsoleOutput] = useState([]);
  const [previewContent, setPreviewContent] = useState("");
  const [previewVisible, setPreviewVisible] = useState(false);

  const generatePreview = (files) => {
    const htmlFile = files.find((f) => f.name.endsWith('.html'));
    const cssFile = files.find((f) => f.name.endsWith('.css'));
    const jsxFile = files.find((f) => f.name.endsWith('.jsx'));
    const jsFile = files.find((f) => f.name.endsWith('.js'));
    const jsFileToUse = jsxFile || jsFile;

    if (htmlFile) {
      let combinedContent = htmlFile.content;
      
      combinedContent = combinedContent.replace(/<link[^>]*rel=['"]stylesheet['"][^>]*>/gi, '');
      combinedContent = combinedContent.replace(/<script[^>]*src=['"][^'"]*\.js['"][^>]*><\/script>/gi, '');

      combinedContent = combinedContent.replace(
        "</head>",
        `  <script crossorigin src="https://cdn.jsdelivr.net/npm/react@18/umd/react.development.js"></script>
  <script crossorigin src="https://cdn.jsdelivr.net/npm/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@babel/standalone/babel.min.js"></script>
  </head>`
      );

      if (cssFile) {
        combinedContent = combinedContent.replace(
          "</head>",
          `  <style>\n${cssFile.content}\n  </style>\n</head>`
        );
      }

      if (jsFileToUse) {
        combinedContent = combinedContent.replace(
          "</body>",
          `  <script type="text/babel" >\n${jsFileToUse.content}\n  </script>\n</body>`
        );
      }

      return combinedContent;
    }
    return "";
  };

  useEffect(() => {
    if (previewVisible) {
      const content = generatePreview(files);
      if (content) {
        setPreviewContent(content);
      }
    }
  }, [files, previewVisible]);

  const runCode = (files) => {
    setConsoleOutput([]);
    const originalLog = console.log;
    const outputs = [];
    let hasError = false;
    
    console.log = (...args) => {
      outputs.push(args.join(" "));
      originalLog(...args);
    };

    const jsFile = files.find((f) => (f.name.endsWith('.js') || f.name.endsWith('.jsx')) && f.active);

    if (jsFile) {
      try {
        const executeCode = new Function(jsFile.content);
        executeCode(); 
        setConsoleOutput(outputs);
      } catch (error) {
        hasError = true;
        if (error.message.includes("Unexpected token '<'")) {
          setConsoleOutput([
            "Note: This console is for pure JavaScript output. If you're trying to observe React JS behavior, please use the preview to see the output.",
            `However, any JavaScript console output generated by React Js code will still be visible in the browser's console.`,
          ]);
        } else {
          setConsoleOutput([`Error: ${error.message}`]);
        }
      } finally {
        console.log = originalLog;
        
        // Emit code execution result for problem solving detection
        window.dispatchEvent(new CustomEvent('codeExecutionResult', {
          detail: {
            success: !hasError,
            error: hasError ? (outputs[0] || 'Unknown error') : null,
            output: outputs
          }
        }));
        
        if (outputs.length === 0) {
          // Check if we're in tests.js file
          const activeFile = files.find(file => file.active);
          const isTestsFile = activeFile?.name === 'tests.js';
          
          if (isTestsFile) {
            setConsoleOutput([
              "Running tests.js - Add executable code to run tests with full JavaScript file context. Individual console.log() calls will appear here when tests run."
            ]);
          } else {
              setConsoleOutput([
              "Add console.log() statements to see output here. Use Run button to execute your JavaScript code. If tests.js has executable code, Run will execute all JavaScript files and tests together."
            ]);
          }
        }
      }
    } else {
      hasError = true;
      setConsoleOutput(["Error: No active JavaScript file found!"]);
      
      // Emit error result
      window.dispatchEvent(new CustomEvent('codeExecutionResult', {
        detail: {
          success: false,
          error: 'No active JavaScript file found!',
          output: []
        }
      }));
    }
    setConsoleState(true);
    hidePreview();
  };

  const showPreview = () => {
    const content = generatePreview(files);
    if (content) {
      setPreviewContent(content);
      setPreviewVisible(true);
    } else {
      alert("index.html file not found!");
    }
  };

  const toggleConsole = () => {
    if (previewVisible) {
      setPreviewVisible(false);
    } else {
      setPreviewVisible(true);
    }
    if (consoleState) {
      setConsoleState(false);
    } else {
      setConsoleState(true);
    }
  };

  const hidePreview = () => {
    setPreviewVisible(false);
  };

  const showConsole = () => {
    setConsoleState(true);
  };

  return {
    consoleState,
    setConsoleState,
    consoleOutput,
    setConsoleOutput,
    runCode,
    showConsole,
    
    previewContent,
    previewVisible,
    showPreview,
    hidePreview,
    
    toggleConsole,
  };
}
