export const accordionTabs = {
  title: "Accordion and Tabs Components",
  description: "Build interactive accordion and tab components with smooth animations and accessibility",
  code_examples: [
    {
      example: "Example 1:",
      code: "class Accordion {\n  constructor(container) {\n    this.container = container;\n    this.items = container.querySelectorAll('.accordion-item');\n    this.init();\n  }\n  \n  init() {\n    this.items.forEach(item => {\n      const header = item.querySelector('.accordion-header');\n      header.addEventListener('click', () => this.toggle(item));\n    });\n  }\n}",
    },
  ],
  hints: [
    {
      hint: "Hint: Use ARIA attributes for accessibility",
    },
    {
      hint: "Consider keyboard navigation and smooth transitions",
    },
  ],
  solution: [
    {
      approach: "Approach 1: Component-based Architecture",
      code: "class AccordionComponent {\n  constructor(element, options = {}) {\n    this.element = element;\n    this.options = { multiple: false, ...options };\n    this.items = [];\n    this.init();\n  }\n  \n  init() {\n    this.setupItems();\n    this.setupEventListeners();\n    this.setupAccessibility();\n  }\n}",
    },
  ],
  files: [
    {
      name: "index.html",
      code: "<!DOCTYPE html>\n<html lang='en'>\n<head>\n  <meta charset='UTF-8'>\n  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n  <title>Accordion and Tabs Components</title>\n  <link rel='stylesheet' href='styles.css'>\n</head>\n<body>\n  <div class='container'>\n    <h1>Accordion and Tabs Components</h1>\n    \n    <div class='component-section'>\n      <h3>Basic Accordion</h3>\n      <div class='accordion' id='basicAccordion'>\n        <div class='accordion-item'>\n          <div class='accordion-header'>\n            <h4>What is JavaScript?</h4>\n            <span class='accordion-icon'>+</span>\n          </div>\n          <div class='accordion-content'>\n            <p>JavaScript is a high-level, interpreted programming language that conforms to the ECMAScript specification.</p>\n          </div>\n        </div>\n        \n        <div class='accordion-item'>\n          <div class='accordion-header'>\n            <h4>How does the DOM work?</h4>\n            <span class='accordion-icon'>+</span>\n          </div>\n          <div class='accordion-content'>\n            <p>The Document Object Model (DOM) is a programming interface for HTML and XML documents.</p>\n          </div>\n        </div>\n      </div>\n    </div>\n    \n    <div class='component-section'>\n      <h3>Basic Tabs</h3>\n      <div class='tabs' id='basicTabs'>\n        <div class='tab-navigation'>\n          <button class='tab-btn active' data-tab='overview'>Overview</button>\n          <button class='tab-btn' data-tab='features'>Features</button>\n          <button class='tab-btn' data-tab='pricing'>Pricing</button>\n        </div>\n        \n        <div class='tab-content'>\n          <div class='tab-panel active' data-panel='overview'>\n            <h3>Overview</h3>\n            <p>Welcome to our amazing product!</p>\n          </div>\n          \n          <div class='tab-panel' data-panel='features'>\n            <h3>Features</h3>\n            <ul>\n              <li>Lightning fast performance</li>\n              <li>Intuitive user interface</li>\n            </ul>\n          </div>\n          \n          <div class='tab-panel' data-panel='pricing'>\n            <h3>Pricing</h3>\n            <div class='pricing-grid'>\n              <div class='pricing-card'>\n                <h4>Basic</h4>\n                <p class='price'>$9/month</p>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n  <script src='script.js'></script>\n</body>\n</html>"
    },
    {
      name: "styles.css",
      code: "* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 2rem; }\n.container { max-width: 800px; margin: 0 auto; background: white; border-radius: 16px; padding: 2rem; box-shadow: 0 20px 40px rgba(0,0,0,0.1); }\nh1 { color: #333; margin-bottom: 2rem; text-align: center; font-size: 2.5rem; }\n.component-section { margin: 3rem 0; padding: 2rem; border: 2px solid #f0f0f0; border-radius: 12px; background: #fafafa; }\n.component-section h3 { color: #666; margin-bottom: 1.5rem; font-size: 1.2rem; text-align: center; }\n\n.accordion { background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n.accordion-item { border-bottom: 1px solid #e9ecef; }\n.accordion-header { display: flex; justify-content: space-between; align-items: center; padding: 1.5rem; cursor: pointer; transition: background-color 0.3s ease; }\n.accordion-header:hover { background-color: #f8f9fa; }\n.accordion-header h4 { color: #333; font-size: 1.1rem; }\n.accordion-icon { width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; background: #667eea; color: white; border-radius: 50%; font-size: 1.2rem; transition: transform 0.3s ease; }\n.accordion-item.active .accordion-icon { transform: rotate(45deg); background: #4ecdc4; }\n.accordion-content { max-height: 0; overflow: hidden; transition: max-height 0.3s ease; }\n.accordion-content > * { padding: 0 1.5rem 1.5rem; }\n.accordion-item.active .accordion-content { max-height: 500px; }\n\n.tabs { background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n.tab-navigation { display: flex; background: #f8f9fa; border-bottom: 1px solid #e9ecef; }\n.tab-btn { flex: 1; padding: 1rem; background: none; border: none; cursor: pointer; font-size: 1rem; color: #666; transition: all 0.3s ease; border-bottom: 3px solid transparent; }\n.tab-btn:hover { background: #e9ecef; color: #333; }\n.tab-btn.active { background: white; color: #667eea; border-bottom-color: #667eea; }\n.tab-content { padding: 2rem; }\n.tab-panel { display: none; }\n.tab-panel.active { display: block; animation: fadeIn 0.3s ease; }\n@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }\n\n.pricing-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }\n.pricing-card { background: #f8f9fa; padding: 1.5rem; border-radius: 8px; text-align: center; }\n.pricing-card h4 { color: #333; margin-bottom: 1rem; }\n.pricing-card .price { font-size: 1.5rem; font-weight: bold; color: #667eea; margin-bottom: 1rem; }"
    },
    {
      name: "script.js",
      code: "class AccordionComponent {\n  constructor(element, options = {}) {\n    this.element = element;\n    this.options = { multiple: false, ...options };\n    this.items = element.querySelectorAll('.accordion-item');\n    this.init();\n  }\n  \n  init() {\n    this.setupItems();\n    this.setupEventListeners();\n  }\n  \n  setupItems() {\n    this.items.forEach(item => {\n      const header = item.querySelector('.accordion-header');\n      const content = item.querySelector('.accordion-content');\n      const icon = item.querySelector('.accordion-icon');\n      \n      item._accordion = { header, content, icon };\n    });\n  }\n  \n  setupEventListeners() {\n    this.items.forEach(item => {\n      const { header } = item._accordion;\n      header.addEventListener('click', () => this.toggle(item));\n    });\n  }\n  \n  toggle(item) {\n    const { content, icon } = item._accordion;\n    const isActive = item.classList.contains('active');\n    \n    if (!this.options.multiple) {\n      this.items.forEach(otherItem => {\n        if (otherItem !== item) {\n          this.close(otherItem);\n        }\n      });\n    }\n    \n    if (isActive) {\n      this.close(item);\n    } else {\n      this.open(item);\n    }\n  }\n  \n  open(item) {\n    const { content, icon } = item._accordion;\n    item.classList.add('active');\n    content.style.maxHeight = content.scrollHeight + 'px';\n    icon.textContent = '-';\n  }\n  \n  close(item) {\n    const { content, icon } = item._accordion;\n    item.classList.remove('active');\n    content.style.maxHeight = '0';\n    icon.textContent = '+';\n  }\n}\n\nclass TabsComponent {\n  constructor(element) {\n    this.element = element;\n    this.tabButtons = element.querySelectorAll('.tab-btn');\n    this.tabPanels = element.querySelectorAll('.tab-panel');\n    this.currentTab = 0;\n    this.init();\n  }\n  \n  init() {\n    this.setupEventListeners();\n  }\n  \n  setupEventListeners() {\n    this.tabButtons.forEach((btn, index) => {\n      btn.addEventListener('click', () => this.showTab(index));\n    });\n  }\n  \n  showTab(index) {\n    const currentPanel = this.tabPanels[this.currentTab];\n    const currentBtn = this.tabButtons[this.currentTab];\n    \n    currentPanel.style.display = 'none';\n    currentBtn.classList.remove('active');\n    \n    const newPanel = this.tabPanels[index];\n    const newBtn = this.tabButtons[index];\n    \n    newPanel.style.display = 'block';\n    newBtn.classList.add('active');\n    \n    this.currentTab = index;\n  }\n}\n\ndocument.addEventListener('DOMContentLoaded', () => {\n  new AccordionComponent(document.getElementById('basicAccordion'));\n  new TabsComponent(document.getElementById('basicTabs'));\n});"
    }
  ],
  tests: [
    {
      test: "Test 1: Accordion initialization",
      code: "const accordion = new AccordionComponent(document.getElementById('accordion'));\nconsole.log('Accordion initialized');"
    }
  ],
};
